# Generated by Django 2.2.5 on 2019-11-06 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_num', models.CharField(default='XXX', max_length=10, unique=True, verbose_name='实验室编号')),
                ('lab_name', models.CharField(default='XXX实验室', max_length=20, verbose_name='实验室名称')),
                ('lab_pic', models.ImageField(default='default.jpg', upload_to='images/labs', verbose_name='实验室照片')),
                ('lab_desc', models.CharField(default='无', max_length=100, verbose_name='实验室描述')),
            ],
            options={
                'verbose_name': '实验室',
                'verbose_name_plural': '实验室',
                'ordering': ['lab_num'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(default='XXXX-XXXX学年度第X学期', max_length=50, unique=True, verbose_name='学期名')),
                ('term_total_weeks', models.IntegerField(default=20, verbose_name='教学周数')),
                ('term_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='起始日期')),
                ('term_end_date', models.DateField(default=django.utils.timezone.now, verbose_name='结束日期')),
                ('term_remark', models.CharField(default='无', max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '学期',
                'verbose_name_plural': '学期',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ord', models.IntegerField(default='0', verbose_name='第几周')),
                ('week_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='起始日期')),
                ('week_end_date', models.DateField(default=django.utils.timezone.now, verbose_name='结束日期')),
                ('week_remark', models.CharField(default='无', max_length=100, verbose_name='备注')),
                ('week_term', models.ForeignKey(on_delete=False, to='timetable.Term', to_field='term_name', verbose_name='学期名')),
            ],
            options={
                'verbose_name': '教学周',
                'verbose_name_plural': '教学周',
                'ordering': ['week_term'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_order', models.CharField(default='未知', max_length=10, verbose_name='预约人')),
                ('book_subject', models.CharField(max_length=10, verbose_name='课程名称')),
                ('book_date', models.DateField(default=django.utils.timezone.now, verbose_name='预约日期')),
                ('book_start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('book_end_time', models.TimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
                ('book_remark', models.CharField(default='无', max_length=100, verbose_name='备注')),
                ('book_lab_num', models.ForeignKey(on_delete=False, to='timetable.Lab', to_field='lab_num', verbose_name='实验室编号')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
            },
        ),
    ]
