# Generated by Django 2.2.5 on 2019-11-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': '实验室安排表', 'verbose_name_plural': '实验室安排表'},
        ),
        migrations.AddField(
            model_name='timetable',
            name='Week_Number',
            field=models.IntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18), ('19', 19)], default=12, verbose_name='周数'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Lab_Number',
            field=models.CharField(choices=[('501', '501'), ('507', '507')], max_length=50, verbose_name='实验室房间号'),
        ),
    ]
