# Generated by Django 2.2.5 on 2019-11-06 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_date',
            field=models.DateField(default=django.utils.timezone.localtime, verbose_name='预约日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_end_time',
            field=models.TimeField(default=django.utils.timezone.localtime, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_start_time',
            field=models.TimeField(default=django.utils.timezone.localtime, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_end_date',
            field=models.DateField(default=django.utils.timezone.localtime, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_start_date',
            field=models.DateField(default=django.utils.timezone.localtime, verbose_name='起始日期'),
        ),
        migrations.AlterField(
            model_name='week',
            name='week_end_date',
            field=models.DateField(default=django.utils.timezone.localtime, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='week',
            name='week_start_date',
            field=models.DateField(default=django.utils.timezone.localtime, verbose_name='起始日期'),
        ),
    ]
