# Generated by Django 2.2.5 on 2019-11-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20191105_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Week_Number',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18), ('19', 19)], default=12, verbose_name='周数'),
        ),
    ]
