# Generated by Django 2.2.5 on 2019-11-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20191105_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='Week_Day',
            field=models.IntegerField(choices=[('周一', 1), ('周二', 2), ('周三', 3), ('周四', 4), ('周五', 5), ('周六', 6), ('周日', 7)], default=1, verbose_name='星期'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Week_Number',
            field=models.IntegerField(choices=[('第1周', 1), ('第2周', 2), ('第3周', 3), ('第4周', 4), ('第5周', 5), ('第6周', 6), ('第7周', 7), ('第8周', 8), ('第9周', 9), ('第10周', 10), ('第11周', 11), ('第12周', 12), ('第13周', 13), ('第14周', 14), ('第15周', 15), ('第16周', 16), ('第17周', 17), ('第18周', 18), ('第19周', 19)], default=12, verbose_name='周数'),
        ),
    ]
