# Generated by Django 2.2.5 on 2019-11-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20191106_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['week_term_name'], 'verbose_name': '教学周', 'verbose_name_plural': '教学周'},
        ),
        migrations.RenameField(
            model_name='week',
            old_name='week_term',
            new_name='week_term_name',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_order',
            field=models.CharField(default='未知预约人', max_length=10, verbose_name='预约人'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_term_name',
            field=models.ForeignKey(default='未知学期', on_delete=False, to='timetable.Term', to_field='term_name', verbose_name='学期'),
        ),
    ]
