# Generated by Django 2.2.5 on 2019-11-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20191105_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Week_Day',
            field=models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期日')], default=1, verbose_name='星期'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Week_Number',
            field=models.IntegerField(choices=[(1, '第1周'), (2, '第2周'), (3, '第3周'), (4, '第4周'), (5, '第5周'), (6, '第6周'), (7, '第7周'), (8, '第8周'), (9, '第9周'), (10, '第10周'), (11, '第11周'), (12, '第12周'), (13, '第13周'), (14, '第14周'), (15, '第15周'), (16, '第16周'), (17, '第17周'), (18, '第18周'), (19, '第19周')], default=12, verbose_name='周数'),
        ),
    ]
